spring:
  application:
    name: FloorSenseBackend

  data:
    mongodb:
      uri: mongodb+srv://admin:adit@cluster0.uyv5apx.mongodb.net/floorsense

claude:
  api-key: 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

elevenlabs:
  api-key: sk_86dd19bef4a0acc056408d27581b7529ddd90f45e81f8878
  voice-id: wBXNqKUATyqu0RtYt25i